apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: portal
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init-db
        image: calvinlogins/portal-image:latest
        imagePullPolicy: Always
        command: ["python", "db_init.py"]
        env:
        - name: DB_HOST
          value: "postgres.default.svc.cluster.local"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
